### ISSUE TITLE
Feature request: ENV variables

### ISSUE THREAD

**Issue by kak-tus** [iph0/Config-Processor#1]
I think, it is a good idea, to add support of environment variables in config.
Usecases:
1. Debug process - we simply do overwriting of some option in config.
2. Configure in production (docker as example intensively uses environment variables). Without this feature we must firstly form config from variable (with consul-template as example) and then use it. And with this feature we can directly start use this config.

**Comment by iph0** [comment]
I should think. Maybe i will implement this feature in the near future

**Comment by iph0** [comment]
Feature was implemented and will be included to next release.
